[build]
  command = "npm run build"
  publish = "dist"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (set these in Netlify UI)
# VITE_API_URL = "https://your-backend-url.onrender.com/api/v1"
